version: '3.8'
services:
  database:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fiap123
      POSTGRES_DB: fiap
    expose:
      - "5432"
  app:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: "fb1dfe4ac7ff13f00ea1c75fe23d895d95fc993952206207d4336af38c558f55"
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: fiap123
      DB_NAME: fiap
    depends_on:
      - database
    restart: on-failure
    #web:
  #  image: nginx
