apiVersion: v1
kind: Service
metadata:
  name: database-svc
spec:
  type: ClusterIP
  selector:
    db: main
  ports:
    - port: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials-secret
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "fiap123"
  POSTGRES_DB: "fiap"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
spec:
  resources:
    requests:
      storage: "10M"
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      db: main
  template:
    metadata:
      name: database-pod
      labels:
        db: main
    spec:
      containers:
        - name: database-container
          image: postgres:16.0-alpine
          ports:
            - containerPort: 5432
              name: database-port
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data-volume
          resources:
            limits:
              cpu: "1.0"
              memory: "512M"
            requests:
              cpu: "0.1"
              memory: "128M"
          envFrom:
            - secretRef:
                name: database-credentials-secret
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $POSTGRES_USER
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: postgres-data-volume
          persistentVolumeClaim:
            claimName: postgres-data-pvc
