apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: web-credentials-secret
stringData:
  JWT_SECRET: "fb1dfe4ac7ff13f00ea1c75fe23d895d95fc993952206207d4336af38c558f55"
  DB_HOST: "database-svc"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "fiap123"
  DB_NAME: "fiap"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: web-pode
      labels:
        app: web
    spec:
      containers:
        - name: web-container
          image: cviniciussdias/grupo61:v0.0.1
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: web-credentials-secret
          resources:
            limits:
              cpu: "0.5"
              memory: "128M"
            requests:
              cpu: "0.1"
              memory: "64M"

