export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const ORDER_REPOSITORY = 'ORDER_REPOSITORY';

export const USER_USE_CASE = 'USER_USE_CASE';
export const PRODUCT_USE_CASE = 'PRODUCT_USE_CASE';
export const ORDER_USE_CASE = 'ORDER_USE_CASE';